language: python
python:
- '3.6'
install:
- pip install pipenv
- SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev
script:
- pipenv run pylint funcake_dags -E
- pipenv run pytest


notifications:
  slack:
    rooms:
      - secure: "aTy/IlNAluK3xJTcElx3AstxCgOmpMHvfkpuMWlul4C6jZN2w4+aWyEzoP31XrTpCNBCB5MNKIw/u4oq8U3TCJAqALP7HB7aR+OxTgS3cGG2xPn4isyGiiYy8WwplgOFTO/La4RQ0+hgScPTLgLHP9iHHwKjYUDr+YBqon+CwLOcyoHItOKxe4dSrYFEpSaf/g0wwZn4PIHvwks6dkhvzF5rXe0v2uY10IcLXLTRjz7AWEvaU9kX1Y9vfx8xw4WF4w8Aj0xRz3uHGi2pvLzVnY0cp229/WUg5vAEpEKav+8P5BkI8XQWpdzlDM8osFSYN8r/JzZIUGbb1eb9rue9cPuCWOgihDAVbsSf222YJcHToE9VpftK//hPBuTXVXumEpF+iicZZQNu5HbIgCjP10NPywEpvLxRUszbsW6/0Ua/t9VaXGSGYLkX3szEgZsvPKQNKD98PgC0p0r9efhg+6So4U3ieou3E3VwzRg/hzI2Cei2TtiDaCeOtJRjeqGcGE+9HmD0hDoktQIX7zhpBPdiK7B8mFJw8q0hgnBNL64jBpRxQxzhn6hyse0sHBpioGTg/S+Z11grtkPy7RtH/9g5bzEx42kGejVPKFQpm9cvfDZCqF9qvUThaNi5Rr4MtLg7Lpl54/UCE88C0nC7Hs/8NIQOlc73/oa0DcKdMXU="
      - secure: "lQK1gchZ+FgFqZyroWaE5Kl0AKy0tioYiVLMO6fP20iowEIhmaTZnDZFoMsLX8Sc2+A7MY+8g8SDkCsUs1/4rUGl9+mC2TJ7mGkFx0CtKl3ZG6zeiH8jMpO0a9SAecfEEg4on754deI8UaQbeEjMyG7/LPKWgFKjxRrUm10FymlQ4RSsNGhO1LM6UwoncoXgJvFLHLkZhhNsG5COTrhLEEbPrxiXgHCX45sa2Yjn2+8zHQCvgcpmqGUgwyNT6oyagIhAH+oZLLeDwxl93SQQ4UFFhTqiQ95mwSL15NkuCI3Xf0X82lgElHbR9XOyFRaRM0QqMGezHk2eR/K4oIhBbMCF8KKubHwJO3CTauFMrfVhhfiPPh5k2WikkOn4zJepsF2Zh0AolPKTftRDcPMuGKf8+2SbDdNm6E5AZtGrXAcpsLsCQbJBNLvhLrDeQXatuuCXOgCgaRBJDgsqTrS/D3xKPoHq3/DAgnTEZSeOfn0KdSanwtXfCWIyf1nH5prGux5LPJ5K4We1Fuc3eUuqeY7+PcgYu99Bn1J2pMq1WEeDWKEoSZiUkGphj5uslmWH3fnVLTKF0F+R6PN9K3AOkeMBTo6CLCzQFiMk5pv9ONaLvF/tYr4m0UmhExCaCgsDakpVuHDcIlETaHVZlyI0YM8QpQ/X2Eqbw/zfEWPM/0U="
